### ISSUE TITLE
The did is not a url for the did, but for a resolution structure which as yet has no name

### ISSUE THREAD

**Issue by TomCJones** [w3c/did-resolution#23] opened 2019-02-08 00:30 UTC
This not only makes the definition of did incorrect, but it points to a need for a name for the structure returned by a did resolution. Would also like to understand how redirects fit into this structure.

**Comment by jandrieu** [comment] 2019-02-08 01:35
The definition definitely needs work. @burnburn and I had some good progress on this topic while working on the DID Explainer today.

To attempt to summarize:

A DID is a URI as per RFC3986 https://tools.ietf.org/html/rfc3986. 
>    A URI can be further classified as a locator, a name, or both.  The
>   term "Uniform Resource Locator" (URL) refers to the subset of URIs
>   that, in addition to identifying a resource, provide a means of
>   locating the resource by describing its primary access mechanism
>   (e.g., its network "location").  ...
>
>   An individual scheme does not have to be classified as being just one
>   of "name" or "locator".  Instances of URIs from any given scheme may
>   have the characteristics of names or locators or both, often
>   depending on the persistence and care in the assignment of
>   identifiers by the naming authority, rather than on any quality of
>   the scheme.  **Future specifications and related documentation should**
>   **use the general term "URI" rather than the more restrictive terms**
>   **"URL" and "URN" [RFC3305].**

I believe it is a fair representation of our discussion to say language like the following should be in the opening section:
> Resolving a DID results in a DID Document, either dynamically generated or retrieved, depending on the method. The DID Document contains the information necessary to dereference the DID to a specific resource. 

Going further, we think the spec should clarify with something like the following language:
> The default dereference of a DID, when no path is specified, MUST return the DID Document. If a path component exists in the DID _and_ that path matches an entry in the services property of the DID Document, dereferencing the DID shall proceed by resolving and dereferencing the matching service endpoint.

And lastly, a suggestion which makes sense to me, but I can't claim any consensus for:
> If there is a path in the DID and the resolution yields a DID Document that lacks a matching service endpoint, dereferencing the DID should yield an error stating clearly that the path has no matching service endpoint.

What that error code is is a whole new kettle of fish. I don't think we've discussed error codes other than a NULL response for a DID that fails to resolve. I expect this won't be the first error code that deserves a more useful response from the resolver. The actual errors should be in the DID-Resolver spec, but the basics of how resolution fits into the relationship between DIDs and DID Documents and the dereferencing thereof, clearly needs to be spelled out in the DID spec.

In general, almost all of us, including me, have been exceedingly unrigorous in how we discuss DIDs "resolving to DID Documents". That is technically correct, but resolution is a process, which yields the information needed to dereference; when we say "resolving to a DID Document" many hear it as "returning the DID Document". However **dereferencing** is what actually returns some sort of resource. We need to improve our language to make this clear from the beginning. 

Here's the relevant quote from RFC3986:
> 1.2.2.  Separating Identification from Interaction

>   A common misunderstanding of URIs is that they are only used to refer
>   to accessible resources.  The URI itself only provides
>   identification; access to the resource is neither guaranteed nor
>   implied by the presence of a URI.  Instead, any operation associated
>   with a URI reference is defined by the protocol element, data format
>   attribute, or natural language text in which it appears.
>
>   Given a URI, a system may attempt to perform a variety of operations
>   on the resource, as might be characterized by words such as "access",
>   "update", "replace", or "find attributes".  Such operations are
>   defined by the protocols that make use of URIs, not by this
>   specification.  However, we do use a few general terms for describing
>   common operations on URIs.  **URI "resolution" is the process of**
>   **determining an access mechanism and the appropriate parameters**
>   **necessary to dereference a URI; this resolution may require several**
>   **iterations.  To use that access mechanism to perform an action on the**
>   **URI's resource is to "dereference" the URI.**

>   When URIs are used within information retrieval systems to identify
>   sources of information, the most common form of URI dereference is
>   "retrieval": making use of a URI in order to retrieve a
>   representation of its associated resource.  A "representation" is a
>   sequence of octets, along with representation metadata describing
>   those octets, that constitutes a record of the state of the resource
>   at the time when the representation is generated.

**Comment by TomCJones** [comment] 2019-02-08 01:39
how about
The default dereference of a DID, when no path is specified, MUST return a claim with the DID Document. If a path component exists in the DID _and_ that path matches an entry in the services property of the DID Document, dereferencing the DID shall proceed by resolving and dereferencing the matching service endpoint.

this is to cover the metadata that comes with the did doc

**Comment by jandrieu** [comment] 2019-02-08 01:53
Interesting. Yes. That's more appropriate. 

Also, a quick read of the DID-Resolution draft states that when a path is specified, instead of resolving and dereferencing the service endpoint, the resolver simply returns the endpoint. That's probably the better default option to remove the load of subsequent dereferencing from the DID resolver. This should probably be selectable, perhaps as intended with the followRedirect parameter, although the current language suggests that only DID service endpoints are redirects. It wouldn't be crazy to support having the resolver optionally resolve and dereference the service endpoints directly, *if* it knows how to. 

However, section 4.1 defining DID Document probably shouldn't use the phrase "retrieved"

**Comment by mwherman2000** [comment] 2019-02-08 02:09
It all depends on what layer of the architecture and to what level of detail you want to discuss this at.  A DID Resolver doesn't return a DID Document to the caller; it returns a DID Resolver Response (which wrapped the returned DID Document).  It's in correct to say that DID Resolution returns a DID Document (unless you have a casual discussion over a coffee or as part of a PowerPoint presentation - but that's not what specifications are about).

Here's a link to the section of the draft INDY ARM that describes the DID Resolution process (also verified by @peacekeeper): 

The "thing" that is returned by the DID Resolver is element (42): a DID Resolver Response.

**Comment by jandrieu** [comment] 2019-02-08 02:12
I think we are in violent agreement. The DID Document is not what is returned by a resolver. Hence we should not define that as such in 4.1

**Comment by mwherman2000** [comment] 2019-02-08 02:15
> I think we are in violent agreement. The DID Document is not what is returned by a resolver. Hence we should not define that as such in 4.1

True but the DID Resolver Response does have to be defined as a "new section 4.1 ...shifting the other elements down one or indented one level to the right in the DID Resolution spec.

**Comment by peacekeeper** [comment] 2024-09-05 16:02
Coming back to this after a while, I wonder how much of it is still relevant. I believe some of what has been discussed in this issue is covered by now in the DID Resolution spec, e.g.

> The default dereference of a DID, when no path is specified, MUST return the DID Document.

I think this is covered by section [DID URL Dereferencing](https://w3c.github.io/did-resolution/#dereferencing).

> a DID Resolver doesn't return a DID Document to the caller; it returns a DID Resolver Response (which, in turn, wraps the returned DID Document)

I think this is covered by section [DID Resolution Result](https://w3c.github.io/did-resolution/#did-resolution-result).

> instead of resolving and dereferencing the service endpoint, the resolver simply returns the endpoint

I think this is covered by section [DID URL Dereferencing](https://w3c.github.io/did-resolution/#dereferencing).

Maybe @TomCJones or @jandrieu could provide their opinion what should be done with this issue.

**Comment by peacekeeper** [comment] 2024-10-10 18:52
Per discussion on today's DID WG call, marking this as pending-close.

**Comment by pchampin** [comment] 2024-10-14 08:38
This was discussed during the [did meeting on 10 October 2024](https://www.w3.org/2024/10/10-did-minutes.html#ca33).

<details><summary><i>View the transcript</i></summary>

<h3>DID Resolution Issue/PR Processing</h3>
<p><cite>burn:</cite> Contact the chairs if anyone would suggest an improvement</p>
<p><cite>markus_sabadello:</cite> let's start with new issues</p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues?q=is%3Aopen+is%3Aissue+label%3Apending-close" rel="noopener noreferrer">https://<wbr>github.com/<wbr>w3c/<wbr>did-resolution/<wbr>issues?q=is%3Aopen+is%3Aissue+label%3Apending-close</a></p>
<p><cite>markus_sabadello:</cite> first with pending close issues</p>
<p><cite>burn:</cite> note that, in the agenda email, we listed these issues.<br>
<span>… We'll be using this process until the end of the thursday meeting to object to the close.</span></p>
<p><cite>&lt;TallTed&gt;</cite> I strongly recommend such searches be ordered by "least recently updated" to keep the churn active, e.g., <a href="https://github.com/w3c/did-resolution/issues?q=is%3Aopen+is%3Aissue+label%3Apending-close+sort%3Aupdated-asc" rel="noopener noreferrer">https://<wbr>github.com/<wbr>w3c/<wbr>did-resolution/<wbr>issues?q=is%3Aopen+is%3Aissue+label%3Apending-close+sort%3Aupdated-asc</a></p>
<p><cite>burn:</cite> the point is, we'll review these quickly today, but the expectation is that you are too look for these in the agenda and speak up or comment in the issue if you have an objection<br>
<span>… so we will not be spending time unless there is a concern (as a general rule)</span></p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/57" rel="noopener noreferrer">w3c/<wbr>did-resolution#57</a></p>
<p><cite>markus_sabadello:</cite> Proposal to rename one of the resolution functions<br>
<span>… Resolve and ResolveStream</span><br>
<span>… This issue is a proposal to rename ResolveStream. That's already happened. I posted a comment 2 weeks ago. No further discussion</span></p>
<p><cite>burn:</cite> any objections to closing?</p>
<p><cite>markus_sabadello:</cite> I'll close them after the call</p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/30" rel="noopener noreferrer">w3c/<wbr>did-resolution#30</a></p>
<p><cite>markus_sabadello:</cite> Issue 30, several years old. Has to do with dereferencing discussion at TPAC<br>
<span>… "The result of dereference can be a DID document, but it can also be something else"</span><br>
<span>… Looking at this issue after a long time, I think the current specification addresses this. I see 3 thumbs up to that comment.</span><br>
<span>… So, if no objections, we'll be closing this.</span></p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/29" rel="noopener noreferrer">w3c/<wbr>did-resolution#29</a></p>
<p><cite>markus_sabadello:</cite> also several years old, about the definition of the term did resolver.<br>
<span>… In the current specification, both terms are defined formally in terminology section. Also two thumbs up.</span><br>
<span>… Any objections?</span></p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/21" rel="noopener noreferrer">w3c/<wbr>did-resolution#21</a></p>
<p><cite>markus_sabadello:</cite> Issue 21 about removing the term DID Reference from DID core to DID Resolution.<br>
<span>… I think this is now obsolete. We don't use that term in any spec.</span><br>
<span>… Same discussion was also in did-core, which was closed. So I think this one can be as well.</span><br>
<span>… Any objections?</span></p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/11" rel="noopener noreferrer">w3c/<wbr>did-resolution#11</a></p>
<p><cite>markus_sabadello:</cite> All methods must have a name of at least three characters.<br>
<span>… This seems like a DID Core issue, not in DID Resolution</span><br>
<span>… Similar issue in DID-core, which has also been closed.</span><br>
<span>… For all of these issues, it seems straightforward to close them.</span><br>
<span>… Since they are older issues, we may not be getting engagement from the initial poster, but unless there are objections, seems like we should close</span></p>
<p><cite>decentralgabe:</cite> If we mark it pending close and give it a week, that would address the older participants</p>
<p><cite>burn:</cite> requirements vary from group to group. In past groups, we've made the point to actively reach out by email and ask for engagement. Then you can comment that in the issue.<br>
<span>… so ping in the issue, then email, then document that email in the issue.</span><br>
<span>… That let's us show we've done what we can to address the concerns of the original poster</span><br>
<span>… For these, I think we're good, but going forward that's a nice improvement to our process</span></p>
<p><cite>burn:</cite> you have 10 more minutes if you like</p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22" rel="noopener noreferrer">https://<wbr>github.com/<wbr>w3c/<wbr>did-resolution/<wbr>issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22</a></p>
<p><cite>markus_sabadello:</cite> one other thing. A few issues are tagged as "Good First Issue"<br>
<span>… Two of them have been assigned. One has not.</span><br>
<span>… These are a good way to contribute, especially if you might not be familiar with deeper technical issues.</span><br>
<span>… We'll try to find more like that and encourage PRs</span><br>
<span>… A few that might be ready to close</span></p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/23" rel="noopener noreferrer">w3c/<wbr>did-resolution#23</a></p>
<p><cite>markus_sabadello:</cite> Issue 23 is about result of dereferencing</p>
<p><cite>&lt;manu&gt;</cite> JoeAndrieu: Looking at the backlog. There is an opportunity here to make a distinction -- how we talk about a DID with and without a trailing slash... but I don't know if that helps us. I need to look at this in more detail, it's five years old, we can close it, if problem still exists, we can raise a new issue again.</p>
<p><cite>&lt;manu&gt;</cite> markus_sabadello: I think this might be obsolete by now?</p>
<p><cite>&lt;manu&gt;</cite> JoeAndrieu: Yeah, sounds like it might be.</p>
<p><cite>&lt;manu&gt;</cite> markus_sabadello: We will have until next call to look at it or raise a new issue if this comes back.</p>
<p><cite>&lt;manu&gt;</cite> JoeAndrieu: Sounds good to me.</p>
<p><cite>manu:</cite> I'm wondering what is the ... I'm fine with closing it. I'm wondering where did we land?<br>
<span>… the response from a resolver is a resolution result, which might contain a did document?</span><br>
<span>… Is that where we landed?</span></p>
<p><cite>markus_sabadello:</cite> that's right the resolution response might contain a did document, but dereferencing might return something else</p>
<p><cite>manu:</cite> i think it's already addressed (as opposed to an older issue that isn't valid)</p>
<p><cite>markus_sabadello:</cite> this was from when we didn't have a did resolution result, we were just returning DID documents<br>
<span>… That has been addressed</span></p>
<p><cite>&lt;JoeAndrieu&gt;</cite> +1</p>
<p><cite>manu:</cite> +1</p>
<p><cite>markus_sabadello:</cite> also to be aware of, from discussions at TPAC, when we talked about path, query, and fragment parts.<br>
<span>… we talked about different patterns in the past and how much of that should be in the resolution spec itself or in did core, or in both.</span><br>
<span>… If people come up with certain features that use the path or query string, how does that fit in and where does it get specified?</span></p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/85" rel="noopener noreferrer">w3c/<wbr>did-resolution#85</a></p>
<p><cite>markus_sabadello:</cite> There are two open issues for new DID parameters with certain functionality</p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/90" rel="noopener noreferrer">w3c/<wbr>did-resolution#90</a></p>
<p><cite>markus_sabadello:</cite> The first introduces version-type the second XYZ as parameters<br>
<span>… Please comment about where these should go and whether or not it should be did-method-specific or standardized across methods</span></p>
<p><cite>burn:</cite> ok, you have about another 5 minutes if you'd like</p>
<p><cite>markus_sabadello:</cite> ok. I'm wondering if we can merge that pull request</p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/pull/89" rel="noopener noreferrer">w3c/<wbr>did-resolution#89</a></p>
<p><cite>markus_sabadello:</cite> or if anyone has new thoughts about the discussion we had about primary resource and secondary resource<br>
<span>… there is an open PR where I tried to improve the headings</span><br>
<span>… to help with that. I'm wondering if people have opinions.</span><br>
<span>… I would actually prefer not to merge because it makes the headings longer</span><br>
<span>… But the algorithm talks about dereferencing the primary resource and secondary resource</span><br>
<span>… This PR adds explanation to the headings</span></p>
<p><cite>manu:</cite> I think it is unfortunate that the initial wording was primary and secondary resource, as that is so abstract it is confusing.<br>
<span>… +1 to comment about section titles get hard</span></p>
<p><cite>&lt;TallTed&gt;</cite> +1 to manu's suggestion</p>
<p><cite>manu:</cite> maybe we can call it derereferencing a DID? or a #fragment<br>
<span>… +1 to not merge this, but maybe we can have did document and fragment as the terms</span></p>
<p><cite>markus_sabadello:</cite> there is something that right now is called a primary resource.<br>
<span>… there needs to be a name for what you get when you dereference the did document</span><br>
<span>… For example, dereferencing the DID URL resource may be a better phrase</span></p>
<p><cite>manu:</cite> yes. that was my thinking. Name the types of things you can dereference.<br>
<span>… A use case where you get a DID Document. A case where you dereference a fragment in a resource. And a third case where it's neither of those.</span><br>
<span>… Related Resource? (Not suggesting that, but if we name it, it will help)</span></p>
<p><cite>markus_sabadello:</cite> this needs to be extensible. we can't imaging all the things they dereference to.<br>
<span>… but i think we can use better terms than Primary &amp; Secondary. I'll try to do that.</span></p>
<p><cite>&lt;manu&gt;</cite> JoeAndrieu: I would like to try my hand at writing this PR, don't know when I'm going to get to it, but want to help.</p>

<hr /></details>

**Comment by pchampin** [comment] 2024-10-17 16:29
This was discussed during the [did meeting on 17 October 2024](https://www.w3.org/2024/10/17-did-minutes.html#67c8).

<details><summary><i>View the transcript</i></summary>

<h4><a href="https://github.com/w3c/did-resolution/issues/23" rel="noopener noreferrer">w3c/<wbr>did-resolution#23</a></h4>
<p><cite>markus_sabadello:</cite> I'll close this at end of meeting, marked it pending close last week, no further comment/objection, closing at end of this call.</p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc" rel="noopener noreferrer">https://<wbr>github.com/<wbr>w3c/<wbr>did-resolution/<wbr>issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc</a></p>
<p><cite>markus_sabadello:</cite> There are a number of older issues, one with the latest input was 22</p>

<hr /></details>

**Closed** 2024-10-18 17:00 UTC
Labels: pending-close
